apiVersion: fn.kptgen.dev/v1alpha1
kind: NADRendererConfig
metadata: # kpt-merge: /nad-renderer-config
  name: nad-renderer-config
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kptgen.dev|NADRendererConfig|default|nad-renderer-config'
spec:
  defaultCNIType: macvlan
  defaultIPAMType: whereabouts
  namingTemplate: "{{ .NetworkName }}-net"
  namespaceIsolation: true
